spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment #로컬환경
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5588

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  #        show_sql: true

